#download AdGuardHome Binary File to path /opt/bin/
#url:https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.59
THISDIR = $(shell pwd)
all:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/adguardhome.sh /usr/bin/adguardhome.sh
